#ifndef __CONST_MENU_CHOSE_SETTINGS__
#define __CONST_MENU_CHOSE_SETTINGS__

#define EKRAN_CHOSE_SETTINGS        (EKRAN_STATE_OUTPUTS + 1)

#define MAX_ROW_FOR_CHOSE_SETTINGS  15

#define INDEX_OF_INFO                     0
#define INDEX_OF_SETTINGS_POINT           1
#define INDEX_OF_INPUTS_RANGUVANNJA       2
#define INDEX_OF_OUTPUTS_RANGUVANNJA      3
#define INDEX_OF_LEDS_RANGUVANNJA         4
#define INDEX_OF_SWITCHER                 5
#define INDEX_OF_TRANSFORMATOR            6
#define INDEX_OF_CONTROL_INPUTS_OUTPUTS   7
#define INDEX_OF_COMMUNICATION            8
#define INDEX_OF_REGISTRATORS             9
#define INDEX_OF_EXTENDED_LOGIC           10
#define INDEX_OF_DEFINED_BUTTONS          11
#define INDEX_OF_GRUPA_USTAVOK            12
#define INDEX_OF_EXTRA_SETTINGS           13
#define INDEX_OF_LIST_PASSWORDS           14

#endif
