#ifndef __CONST_MENU_CHOSE_SETTINGS_REGISTRATORS__
#define __CONST_MENU_CHOSE_SETTINGS_REGISTRATORS__

#define EKRAN_VIEW_LIST_OF_REGISTRATORS             (EKRAN_VIEW_TIMEOUT_RS485 + 1)
#define EKRAN_RANGUVANNJA_DIGITAL_REGISTRATOR       (EKRAN_VIEW_LIST_OF_REGISTRATORS + 1)
#define EKRAN_VIEW_SETTINGS_OF_ANALOG_REGISTRATORS  (EKRAN_RANGUVANNJA_DIGITAL_REGISTRATOR + 1)
#define EKRAN_RANGUVANNJA_ANALOG_REGISTRATOR        (EKRAN_VIEW_SETTINGS_OF_ANALOG_REGISTRATORS + 1)
#define EKRAN_TIMEOUT_ANALOG_REGISTRATOR            (EKRAN_RANGUVANNJA_ANALOG_REGISTRATOR  + 1)

#define MAX_ROW_FOR_LIST_OF_REGISTRATORS             2
#define MAX_ROW_RANGUVANNJA_DIGITAL_REGISTRATOR      NUMBER_TOTAL_SIGNAL_FOR_RANG
#define MAX_ROW_FOR_SETTINGS_OF_ANALOG_REGISTRATOR   2
#define MAX_ROW_FOR_TIMEOUT_ANALOG_REGISTRATOR       2
#define MAX_ROW_RANGUVANNJA_ANALOG_REGISTRATOR       NUMBER_TOTAL_SIGNAL_FOR_RANG

#define INDEX_ML_DIGITAL_REGISTRATOR                 0
#define INDEX_ML_ANALOG_REGISTRATOR                  1

#define INDEX_ML_SOURCE_ANALOG_REGISTRATOR           0
#define INDEX_ML_TIMEOUT_ANALOG_REGISTRATOR          1

#define INDEX_ML_TMOPREFAULT                         0
#define INDEX_ML_TMOPOSTFAULT                        1

#define COL_TMO_PREFAULT_BEGIN                       5
#define COL_TMO_PREFAULT_COMMA                       6
#define COL_TMO_PREFAULT_END                         8

#define COL_TMO_POSTFAULT_BEGIN                      4
#define COL_TMO_POSTFAULT_COMMA                      6
#define COL_TMO_POSTFAULT_END                        8


#endif
